/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtualizacoesRouteImport } from './routes/atualizacoes'
import { Route as EncerramentoRouteImport } from './routes/encerramento'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as NormasRouteImport } from './routes/normas'
import { Route as CapituloNRouteImport } from './routes/capitulo.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizacoesRoute = AtualizacoesRouteImport.update({
  id: '/atualizacoes',
  path: '/atualizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EncerramentoRoute = EncerramentoRouteImport.update({
  id: '/encerramento',
  path: '/encerramento',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const NormasRoute = NormasRouteImport.update({
  id: '/normas',
  path: '/normas',
  getParentRoute: () => rootRouteImport,
} as any)
const CapituloNRoute = CapituloNRouteImport.update({
  id: '/capitulo/$n',
  path: '/capitulo/$n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/encerramento': typeof EncerramentoRoute
  '/ferramentas': typeof FerramentasRoute
  '/guia': typeof GuiaRoute
  '/normas': typeof NormasRoute
  '/capitulo/$n': typeof CapituloNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/encerramento': typeof EncerramentoRoute
  '/ferramentas': typeof FerramentasRoute
  '/guia': typeof GuiaRoute
  '/normas': typeof NormasRoute
  '/capitulo/$n': typeof CapituloNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/encerramento': typeof EncerramentoRoute
  '/ferramentas': typeof FerramentasRoute
  '/guia': typeof GuiaRoute
  '/normas': typeof NormasRoute
  '/capitulo/$n': typeof CapituloNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atualizacoes'
    | '/encerramento'
    | '/ferramentas'
    | '/guia'
    | '/normas'
    | '/capitulo/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizacoes'
    | '/encerramento'
    | '/ferramentas'
    | '/guia'
    | '/normas'
    | '/capitulo/$n'
  id:
    | '__root__'
    | '/'
    | '/atualizacoes'
    | '/encerramento'
    | '/ferramentas'
    | '/guia'
    | '/normas'
    | '/capitulo/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtualizacoesRoute: typeof AtualizacoesRoute
  EncerramentoRoute: typeof EncerramentoRoute
  FerramentasRoute: typeof FerramentasRoute
  GuiaRoute: typeof GuiaRoute
  NormasRoute: typeof NormasRoute
  CapituloNRoute: typeof CapituloNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizacoes': {
      id: '/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AtualizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encerramento': {
      id: '/encerramento'
      path: '/encerramento'
      fullPath: '/encerramento'
      preLoaderRoute: typeof EncerramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normas': {
      id: '/normas'
      path: '/normas'
      fullPath: '/normas'
      preLoaderRoute: typeof NormasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capitulo/$n': {
      id: '/capitulo/$n'
      path: '/capitulo/$n'
      fullPath: '/capitulo/$n'
      preLoaderRoute: typeof CapituloNRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtualizacoesRoute: AtualizacoesRoute,
  EncerramentoRoute: EncerramentoRoute,
  FerramentasRoute: FerramentasRoute,
  GuiaRoute: GuiaRoute,
  NormasRoute: NormasRoute,
  CapituloNRoute: CapituloNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
